version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: vinicius123
    ports:
      - "5432:5432"
    volumes:
      - meu_volume:/var/lib/postgresql/data

volumes:
  meu_volume:
